/*
                                                      
    template-plugin
         Copyright © 2026 by Mateus Mesquita Lima

    -» Author    	       : Mateus Mesquita Lima / mateus-bsod
    -» Release Date	       : 15 Jan 2026
    -» Description	       : Include / Plugin

*/

//           TEMPLATE_PLUGIN
#if defined _TEMPLATE_PLUGIN_included
    #endinput
#endif
#define _TEMPLATE_PLUGIN_included

/*

                    _____  __ __  ____     __ ______  ____  ___   ____   _____
                    |     ||  |  ||    \   /  ]      ||    |/   \ |    \ / ___/
                    |   __||  |  ||  _  | /  /|      | |  ||     ||  _  (   \_ 
                    |  |_  |  |  ||  |  |/  / |_|  |_| |  ||  O  ||  |  |\__  |
                    |   _] |  :  ||  |  /   \_  |  |   |  ||     ||  |  |/  \ |
                    |  |   |     ||  |  \     | |  |   |  ||     ||  |  |\    |
                    |__|    \__,_||__|__|\____| |__|  |____|\___/ |__|__| \___|

                    ___________________________________________________________                           

*/

native HelloWorld();
